apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-app-blue
  labels:
    app: messaging-app
    version: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messaging-app
      version: blue
  template:
    metadata:
      labels:
        app: messaging-app
        version: blue
    spec:
      containers:
        - name: messaging-app-container
          image: buomyian/messaging-app:blue
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: "messaging_app.settings"

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: messaging-app-service
# spec:
#   type: ClusterIP
#   selector:
#     app: messaging-app
#   ports:
#     - name: http
#       port: 8000
#       targetPort: 8080
